# Generated by Django 4.2.6 on 2023-10-19 23:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('Eastern', 'Eatern'), ('Northern', 'Northern'), ('North East', 'North East'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=50)),
                ('city', models.CharField(choices=[('Kailauhun', 'Kailahun'), ('Kenema', 'Kenema'), ('Freetown', 'Freetown'), ('Koidu Town', 'Koidu Town'), ('WaterLoo', 'WaterLoo'), ('Makeni', 'Makeni'), ('Magburaka', 'Magburaka'), ('Kambia', 'Kambia'), ('Kabala', 'Kabala'), ('Kamakwie', 'Kamakwie'), ('Bo', 'Bo'), ('Bonth', 'Bonth'), ('Moyamba', 'Moyamba'), ('Pujehun', 'Pujehun'), ('Bendugu', 'Bendugu'), ('Port Loko', 'Port Loko')], max_length=50)),
                ('district', models.CharField(choices=[('Kailauhun', 'Kailahun'), ('Kenema', 'Kenema'), ('Kono', 'Kono'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('koinadugu', 'Koinadugu'), ('Tonkolili', 'Tokolili'), ('Kambia', 'Kambia'), ('Karene', 'Karene'), ('PortLoko', 'PortLoko'), ('Bo', 'Bo'), ('Bonth', 'Bonth'), ('Moyamba', 'Moyamba'), ('Pujehun', 'Pujehun'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Wester Urban')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrtor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Registration Officer'),
        ),
        migrations.CreateModel(
            name='Regcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crms.address')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIN', models.CharField(max_length=50, unique=True)),
                ('First_name', models.CharField(max_length=50)),
                ('Middle_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Others')], max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('DOB', models.DateField(null=True)),
                ('fathername', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
                ('Contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('citizenship', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='profile_pics/')),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crms.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
