# Generated by Django 4.2.6 on 2023-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0002_address_remove_user_is_customer_alter_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='NIN',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
