# Generated by Django 4.2.6 on 2023-10-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0003_alter_customers_nin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
