# Generated by Django 4.2.6 on 2023-10-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0004_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='First_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Last_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Middle_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='NIN',
            new_name='nin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Kailauhun', 'Kailahun'), ('Kenema', 'Kenema'), ('Freetown', 'Freetown'), ('Koidu Town', 'Koidu Town'), ('WaterLoo', 'WaterLoo'), ('Makeni', 'Makeni'), ('Magburaka', 'Magburaka'), ('Kambia', 'Kambia'), ('Kabala', 'Kabala'), ('Kamakwie', 'Kamakwie'), ('Bo', 'Bo'), ('Bonth', 'Bonth'), ('Moyamba', 'Moyamba'), ('Pujehun', 'Pujehun'), ('Bendugu', 'Bendugu'), ('Port Loko', 'Port Loko')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('Kailauhun', 'Kailahun'), ('Kenema', 'Kenema'), ('Kono', 'Kono'), ('Bombali', 'Bombali'), ('Falaba', 'Falaba'), ('koinadugu', 'Koinadugu'), ('Tonkolili', 'Tokolili'), ('Kambia', 'Kambia'), ('Karene', 'Karene'), ('PortLoko', 'PortLoko'), ('Bo', 'Bo'), ('Bonth', 'Bonth'), ('Moyamba', 'Moyamba'), ('Pujehun', 'Pujehun'), ('Western Rural', 'Western Rural'), ('Western Urban', 'Wester Urban')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('Eastern', 'Eatern'), ('Northern', 'Northern'), ('North East', 'North East'), ('Southern', 'Southern'), ('Western', 'Western')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
