# Generated by Django 4.2.6 on 2023-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0006_customer_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registereddate',
            field=models.DateField(null=True),
        ),
    ]
