# Generated by Django 4.2.6 on 2023-10-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
