# Generated by Django 4.2.6 on 2023-10-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0011_alter_customer_citizenship_alter_customer_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='citizenship',
            field=models.CharField(default='SIERRA LEONEAN', max_length=50),
        ),
    ]
