# Generated by Django 4.2.6 on 2023-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0014_rename_cause_ofdeath_deathreg_cause_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathreg',
            name='photo',
            field=models.ImageField(default='', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
