# Generated by Django 4.2.6 on 2023-10-31 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0016_alter_customer_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
