# Generated by Django 4.2.6 on 2023-10-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0017_alter_customer_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
