# Generated by Django 4.2.6 on 2023-10-31 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0019_alter_customer_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
