# Generated by Django 4.2.6 on 2023-10-31 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0020_alter_customer_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
