# Generated by Django 4.2.6 on 2023-11-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0021_alter_customer_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='registereddate',
            new_name='registered_date',
        ),
    ]
