# Generated by Django 4.2.6 on 2023-11-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0023_alter_customer_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deathreg',
            old_name='registereddate',
            new_name='registered_date',
        ),
    ]
