# Generated by Django 4.2.6 on 2023-11-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0025_customer_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qrcode',
        ),
    ]
