# Generated by Django 4.2.6 on 2023-11-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0027_customer_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qr_code',
        ),
    ]
