# Generated by Django 4.2.6 on 2023-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0028_remove_customer_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathreg',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
